### ISSUE TITLE
hexo server 何为无法运行项目

### ISSUE THREAD

**Issue by br2me** [litten/hexo-theme-yilia#599]
完全没仔细看项目，后来发现是theme，理解了~~

**Comment by tempwork** [comment]
目录如下：

>  G:\Svn\hexo-theme-yilia-master 的目录

2017/08/27  22:33    <DIR>          .
2017/08/27  22:33    <DIR>          ..
2017/07/09  02:14               116 .babelrc
2017/07/09  02:14               147 .editorconfig
2017/07/09  02:14                23 .eslintignore
2017/07/09  02:14               738 .eslintrc.js
2017/07/09  02:14               175 .gitattributes
2017/07/09  02:14               113 .gitignore
2017/07/09  02:14    <DIR>          languages
2017/07/09  02:14    <DIR>          layout
2017/08/27  21:05    <DIR>          node_modules
2017/08/27  22:33                 0 npm-debug.log.252347926
2017/07/09  02:14             1,532 package.json
2017/07/09  02:14             5,421 README.md
2017/08/27  21:05    <DIR>          source
2017/07/09  02:14    <DIR>          source-src
2017/07/09  02:14             2,496 webpack.config.js
2017/07/09  02:14             2,965 _config.yml
              11 个文件         13,726 字节

是在git clone到本地解压后的项目根目录执行了npm install后就hexo server，但报以下错误，多次尝试也不行，通过自己hexo init 新建的项目是可以跑起来的

G:\Svn\hexo-theme-yilia-master>hexo server
Usage: hexo <command>

Commands:
  help     Get help on a command.
  init     Create a new Hexo folder.
  version  Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/
